config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  resources :rooms do
    resources :question_answers do
      member do
        patch :increment_study_count
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question_answer.rb
class QuestionAnswer < ApplicationRecord

  validates :study_count, presence: true

  belongs_to :room
  has_many_attached :question_images
  has_many_attached :answer_images

end

app/models/room.rb
class Room < ApplicationRecord

  belongs_to :user
  has_many :question_answers, dependent: :destroy

  def has_low_study_count_question_answer?
    question_answers.where('study_count < ?', 5).exists?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, unless: :devise_controller?

  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end


end

app/controllers/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    def search_question_answers(scope)
      if params[:title].present?
        scope = scope.where(title: params[:title])
      end

      if params[:word].present?
        scope = scope.where("title LIKE :word OR question LIKE :word OR answer LIKE :word", word: "%#{params[:word]}%")
      end

      scope
    end
  end
end

app/controllers/question_answers_controller.rb
class QuestionAnswersController < ApplicationController

  include Searchable
  before_action :set_room
  before_action :set_question_answer, only: [:edit, :update]
  before_action :return_action

  def index
    @study_count_plus1 = (params[:study_count].to_i) + 1
    @question_answers = @room.question_answers

    if params[:study_count]
      time_limit = 3.hours.ago
      if params[:study_count] == '10+'
        @question_answers = @question_answers.where("study_count >= ? AND updated_at <= ?", 10, time_limit)
      elsif params[:study_count] == '5~9'
        @question_answers = @question_answers.where(study_count: 5..9).where("updated_at <= ?", time_limit)
      elsif params[:study_count] == '0~4'
        @question_answers = @question_answers.where(study_count: 0..4).where("updated_at <= ?", time_limit)
      else
        @question_answers = @question_answers.where(study_count: params[:study_count])
      end
    end

    if session[:search_title].present?
      @question_answers = @question_answers.where(title: session[:search_title])
    end

    if session[:search_word].present?
      @question_answers = @question_answers.where("title LIKE :word OR question LIKE :word OR answer LIKE :word", word: "%#{session[:search_word]}%")
    end

    count = @question_answers.count
    @random_question_answer = @question_answers.offset(rand(count)).first if count > 0
  end

  def new
    @titles = @room.question_answers.select(:title).distinct.order(:title)
    @question_answer = @room.question_answers.new
  end

  def create
    @question_answer = @room.question_answers.new(question_answer_params)
    @question_answer.study_count = 0
    if @question_answer.save
      redirect_to room_path(@room, title: session[:search_title], word: session[:search_word])
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @titles = @room.question_answers.select(:title).distinct.order(:title)
    render 'new'
  end

  def update
    # 質問用の画像削除
    if params[:question_answer][:question_images_to_delete].present?
      params[:question_answer][:question_images_to_delete].each do |image_id|
        image = @question_answer.question_images.find(image_id)
        image.purge if image
      end
    end

    # 回答用の画像削除
    if params[:question_answer][:answer_images_to_delete].present?
      params[:question_answer][:answer_images_to_delete].each do |image_id|
        image = @question_answer.answer_images.find(image_id)
        image.purge if image
      end
    end

    # 質問用の新しい画像を追加
    unless params[:question_answer][:question_images].reject(&:blank?).empty?
      @question_answer.question_images.attach(params[:question_answer][:question_images].reject(&:blank?))
    end

    # 回答用の新しい画像を追加
    unless params[:question_answer][:answer_images].reject(&:blank?).empty?
      @question_answer.answer_images.attach(params[:question_answer][:answer_images].reject(&:blank?))
    end

    # パラメータの更新
    updated_params = question_answer_params.except(:question_images, :question_images_to_delete, :answer_images, :answer_images_to_delete)
    

    if @question_answer.update(updated_params)
      redirect_to room_path(@room, title: session[:search_title], word: session[:search_word])
    else
      render :new, status: :unprocessable_entity
    end
  end

  def increment_study_count
    @random_question_answer = QuestionAnswer.find(params[:id])
    @random_question_answer.increment!(:study_count)
    @random_question_answer.touch
    redirect_to room_question_answer_path(@room, @random_question_answer)
  end

  def destroy
    question_answer = @room.question_answers.find(params[:id])
    question_answer.destroy
    redirect_to room_path(@room, title: session[:search_title], word: session[:search_word])
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_question_answer
    @question_answer = @room.question_answers.find(params[:id])
  end

  def question_answer_params
    params.require(:question_answer).permit(:question, :answer, :title, :study_count, :room_id, question_images: [], question_images_to_delete: [], answer_images: [], answer_images_to_delete: [])
  end

  def return_action
    return unless current_user.id == @room.user_id
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  include Searchable
  before_action :set_room, only: [:edit, :update, :show]
  before_action :return_action, only: [:edit, :update, :show]

  def index
    @rooms = Room.all.includes(:question_answers)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    render 'new'
  end

  def update
    if @room.update(room_params)
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    room = Room.find(params[:id])
    return unless current_user.id == room.user_id
    room.destroy
    redirect_to root_path
  end

  def show
    if params[:title].present?
      session[:search_title] = params[:title]
    else
      session.delete(:search_title)
    end

    if params[:word].present?
      session[:search_word] = params[:word]
    else
      session.delete(:search_word)
    end

    @question_answers = search_question_answers(@room.question_answers.order(study_count: :asc))
    @titles = @room.question_answers.select(:title).distinct.order(:title)
    question_count
  end


  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:room_name, :room_number).merge(user_id: current_user.id)
  end

  def question_count
    @study_counts = @question_answers.group(:study_count).count
  end

  def return_action
    return unless current_user.id == @room.user_id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_answers_helper.rb
module QuestionAnswersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyFive</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/question_answers/index.html.erb
<div class="q-a-top-text-box">
  <div class="q-a-top-text">
    Q&A
  </div>
  <% if @random_question_answer %>
    <%= @random_question_answer.study_count+1 %>回目の問題
  <% end %>
</div>
<br>
<div class="back-link">
  <%= link_to "Back", room_path(@room, title: session[:search_title], word: session[:search_word]) %>
</div>
<br><br>
<div class="study-question-answer-box">
  <% if @random_question_answer %>
    <div class="study-question-answer-title-box">
      Title
      <div class="study-question-answer-title-text-box">
        <%= simple_format(@random_question_answer.title) %>
      </div>
    </div>

    <div class="study-question-answer-question-box">
      Question
      <div class="study-question-answer-question-text-and-images-box-border">
        <div class="study-question-answer-question-text-and-images-box">
          <div class="study-question-answer-question-text-box">
            <%= simple_format(@random_question_answer.question) %>
          </div>
          <div class="study-question-answer-multi-images-box">
            <% @random_question_answer.question_images.each do |image| %>
              <div class="study-question-answer-image-box">
                <%= image_tag image %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>


    <div class="study-question-answer-answer-box">
      Answer
      <div class="study-question-answer-answer-text-and-images-box-border">
        <div class="study-question-answer-answer-text-and-images-box">
          <div class="study-question-answer-answer-text-box">
            <%= simple_format(@random_question_answer.answer) %>
          </div>
          <div class="study-question-answer-multi-images-box">
            <% @random_question_answer.answer_images.each do |image| %>
              <div class="study-question-answer-image-box">
                <%= image_tag image %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>





  <% else %>
    <% if @study_count_plus1 %>
      <% if params[:study_count] == '0~4' %>
        <p>最終更新時から3時間経過後の</p>
        <p>1~5回目の問題が見つかりません。</p>
      <% elsif @study_count_plus1 < 6 %>
        <p><%= @study_count_plus1 %>回目の問題が見つかりません。</p>
      <% elsif @study_count_plus1 < 11 %>
        <p>最終更新時から3時間経過後の</p>
        <p>6~10回目の問題が見つかりません。</p>
      <% else %>
        <p>最終更新時から3時間経過後の</p>
        <p>11回目以上の問題が見つかりません。</p>
      <% end %>
    <% end %>
  <% end %>
</div>





<% if @random_question_answer %>
  <div class="question-answer-next-btn">
    <%= form_with url: increment_study_count_room_question_answer_path(@room, @random_question_answer), method: :patch do |form| %>
      <%= form.submit "次のQ&A", class: 'question-answer-next-submit' %>
    <% end %>
  </div>
 <% end %>

app/views/question_answers/new.html.erb

<div class="question-create-update-top-text">
  <% if @question_answer.persisted? %>
    <h1>Q&A編集ページ</h1>
  <% else %>
    <h1>Q&A作成ページ</h1>
  <% end %>
</div>

<div class="back-link">
  <%= link_to "Back", room_path(@room, title: session[:search_title], word: session[:search_word]) %>
</div>
<br><br>
<%= form_with model: [@room, @question_answer], local: true do |f| %>
  <div class="question_answer-form-box">
    <div class="title-form-and-existing-title-box">
    <div class="title-form-box">
      Title
      <%= f.text_area :title, class: 'title-form', id: 'title_text_area', placeholder: '' %>
    </div>
    <div class="existing-title-box">
    <%= label_tag :title2, "existing title", class: 'question_answer-copy-label' %>
    <%= select_tag :title2, options_from_collection_for_select(@titles, 'title', 'title', selected: params[:title2]), include_blank: true, class: 'question_answer-create-copy-title-list', id: 'title2_select' %>
    </div>
    </div>
    <div class="question-form-box">
      Question
      <%= f.text_area :question, class: 'question-form', placeholder: '' %>
    </div>

<%# 問題用のイメージアップロードフォーム %>
    <div class="question-image-upload-form-box">
      <strong>Question Images:</strong>
      <% if @question_answer.question_images.attached? %>
        <% @question_answer.question_images.each do |image| %>
          <div class="existing-image">
            <%= image_tag(image) %>
            <%= check_box_tag "question_answer[question_images_to_delete][]", image.id %>
            <%= label_tag "削除する" %>
          </div>
        <% end %>
      <% end %>
      <%= f.file_field :question_images, multiple: true, accept: 'image/png,image/jpeg,image/gif', direct_upload: true, class: 'image-form' %>
    </div>

    <div class="answer-form-box">
      Answer
      <%= f.text_area :answer, class: 'answer-form', placeholder: '' %>
    </div>


<%# 解答用のイメージアップロードフォーム %>
        <div class="answer-image-upload-form-box" style="background-color: #e8f5e9;">
      <strong>Answer Images:</strong>
      <% if @question_answer.answer_images.attached? %>
        <% @question_answer.answer_images.each do |image| %>
          <div class="existing-image">
            <%= image_tag(image) %>
            <%= check_box_tag "question_answer[answer_images_to_delete][]", image.id %>
            <%= label_tag "削除する" %>
          </div>
        <% end %>
      <% end %>
      <%= f.file_field :answer_images, multiple: true, accept: 'image/png,image/jpeg,image/gif', direct_upload: true, class: 'image-form' %>
    </div>


    <div class="study_count-form-submit-box">
      <% if @question_answer.persisted? %>
        <div class="study_count-form-box">
          Count
          <%= f.text_field :study_count, class: 'study_count-form' %>
        </div>
      <% end %>
        <div class="question-answer-submit-box-space">
        </div>
        <div>
        <%= hidden_field_tag :title, session[:search_title] %>
        <%= hidden_field_tag :word, session[:search_word] %>
        <%= f.submit @question_answer.new_record? ? 'Create' : 'Update', class: 'question-answer-submit' %>
        </div>
    </div>
  </div>
<% end %>

app/views/rooms/index.html.erb
<h1>トップページ</h1>

<div class="room-create-link">
<%= link_to "Create Room", new_room_path %>
</div>

<br><br>

<% @rooms.each do |room| %>
  <div class="room-list">
    <div class="room-link">
      ・<%= link_to room.room_name, room_path(room) %>
    </div>
    <div class="room-link">
      <%= "☆" if room.has_low_study_count_question_answer? %>
    </div>
    <div class="room-edit-link">
      <%= link_to "Edit", edit_room_path(room) %>
    </div>
    <div class="room-delete-link">
      <%= link_to "Delete", room_path(room), data: { turbo_method: :delete, turbo_confirm: "このルーム内のQ&Aもすべて無くなりますが、削除してよろしいですか？"} %>
    </div>
  </div>
<% end %>

app/views/rooms/new.html.erb
<h1>Create Room</h1>

<div class="back-link">
  <%= link_to "Back", root_path %>
</div>
<%= form_with model: @room, local: true do |f| %>
  <div class="room-create-form-box">
    <div class="room-name-form-box">
      <%= f.text_field :room_name, class: 'room-name-form', placeholder: 'Room Name' %>
    </div>
    <div class="room-create-submit-box">
      <%= f.submit @room.new_record? ? 'Create' : 'Update', class: 'room-create-submit' %>
    </div>
  </div>
<% end %>

app/views/rooms/show.html.erb
<h1><%= @room.room_name %></h1>

<div class="back-link">
  <%= link_to "Back", root_path %>
</div>
<br><br>

<div class="practice-link-list">
  <div class="practice-link">
    <div class="practice-count-display">
      <%= link_to "全問題", room_question_answers_path(@room) %>
    </div>
    <div class="practice-question-count">
      <% count = @question_answers.count %>
      <span class="<%= count.zero? ? 'white-text' : 'enamel-green-text' %>"><%= count %></span>
      問
    </div>
  </div>
  <div class="practice-link">
    <div class="practice-count-display">
      <%= link_to "1~5回目", room_question_answers_path(@room, study_count: "0~4", title: session[:search_title], word: session[:search_word]) %>
    </div>
    <div class="practice-question-count">
      <% count = @study_counts.select { |key, value| key >= 0 && key < 5}.values.sum || 0 %>
      <span class="<%= count.zero? ? 'white-text' : 'enamel-green-text' %>"><%= count %></span>
      問
    </div>
  </div>
  <div class="practice-link">
    <div class="practice-count-display">
      <%= link_to "6~10回目", room_question_answers_path(@room, study_count: "5~9", title: session[:search_title], word: session[:search_word]) %>
    </div>
    <div class="practice-question-count">
      <% count = @study_counts.select { |key, value| key >= 5 && key < 10}.values.sum || 0 %>
      <span class="<%= count.zero? ? 'white-text' : 'enamel-green-text' %>"><%= count %></span>
      問
    </div>
  </div>
  <div class="practice-link">
    <div class="practice-count-display">
      <%= link_to "11回目以上", room_question_answers_path(@room, study_count: "10+", title: session[:search_title], word: session[:search_word]) %>
    </div>
    <div class="practice-question-count">
      <% count = @study_counts.select { |key, value| key >= 10 }.values.sum || 0 %>
      <span class="<%= count.zero? ? 'white-text' : 'enamel-green-text' %>"><%= count %></span>
      問
    </div>
  </div>
</div>

<br>

<div class="practice-link-list">
  <div class="practice-link">
    <div class="practice-count-display">
      <%= link_to "問題 1回目", room_question_answers_path(@room, study_count: 0, title: session[:search_title], word: session[:search_word]) %>
    </div>
    <div class="practice-question-count">
      <% count = @study_counts[0] || 0 %>
      <span class="<%= count.zero? ? 'white-text' : 'enamel-green-text' %>"><%= count %></span>
      問
    </div>
  </div>
  <div class="practice-link">
    <div class="practice-count-display">
      <%= link_to "問題 2回目", room_question_answers_path(@room, study_count: 1, title: session[:search_title], word: session[:search_word]) %>
    </div>
    <div class="practice-question-count">
      <% count = @study_counts[1] || 0 %>
      <span class="<%= count.zero? ? 'white-text' : 'enamel-green-text' %>"><%= count %></span>
      問
    </div>
  </div>
  <div class="practice-link">
    <div class="practice-count-display">
      <%= link_to "問題 3回目", room_question_answers_path(@room, study_count: 2, title: session[:search_title], word: session[:search_word]) %>
    </div>
    <div class="practice-question-count">
      <% count = @study_counts[2] || 0 %>
      <span class="<%= count.zero? ? 'white-text' : 'enamel-green-text' %>"><%= count %></span>
      問
    </div>
  </div>
  <div class="practice-link">
    <div class="practice-count-display">
      <%= link_to "問題 4回目", room_question_answers_path(@room, study_count: 3, title: session[:search_title], word: session[:search_word]) %>
    </div>
    <div class="practice-question-count">
      <% count = @study_counts[3] || 0 %>
      <span class="<%= count.zero? ? 'white-text' : 'enamel-green-text' %>"><%= count %></span>
      問
    </div>
  </div>
  <div class="practice-link">
    <div class="practice-count-display">
      <%= link_to "問題 5回目", room_question_answers_path(@room, study_count: 4, title: session[:search_title], word: session[:search_word]) %>
    </div>
    <div class="practice-question-count">
      <% count = @study_counts[4] || 0 %>
      <span class="<%= count.zero? ? 'white-text' : 'enamel-green-text' %>"><%= count %></span>
      問
    </div>
  </div>
</div>

<br>

<div class="question-create-link">
  <%= link_to "Create Question", new_room_question_answer_path(@room, title: session[:search_title], word: session[:search_word]) %>
</div>

<br><br>

<div class="question_answer-search-box">
  <%= form_with url: room_path(@room), method: :get, local: true do %>
    <div class="search-field">
      <%= hidden_field_tag :word, params[:word] %>
      <%= label_tag :title, "Select a title", class: 'question_answer-search-label' %>
      <%= select_tag :title, options_from_collection_for_select(@titles, 'title', 'title', selected: params[:title]), include_blank: true, class: 'question_answer-search-title-list' %>
      <%= submit_tag "Title Search", class: 'question_answer-search-do-button' %>
    </div>
  <% end %>

  <%= form_with url: room_path(@room), method: :get, local: true do %>
    <div class="search-field">
      <%= hidden_field_tag :title, params[:title] %>
      <%= label_tag :word, "Word Search", class: 'question_answer-search-label' %>
      <%= text_field_tag :word, params[:word], class: 'question_answer-word-search-bar', value: params[:word], placeholder: '' %>
      <%= submit_tag "Word Search", class: 'question_answer-search-do-button' %>
    </div>
  <% end %>
</div>

<div class="room-top-question-answer-box">
  <% @question_answers.each do |question_answer| %>
    <div class="room-top-question-answer">
      <div class="room-top-title">
        <%= simple_format(question_answer.title) %>
      </div>
      <div class="room-top-question">
        <%= simple_format(question_answer.question) %>
      </div>
      <div class="room-top-answer">
        <%= simple_format(question_answer.answer) %>
      </div>
      <div class="room-top-study_count">
        <%= question_answer.study_count %>
      </div>
      <div class="question-edit-link">
        <%= link_to "Edit", edit_room_question_answer_path(@room, question_answer, title: session[:search_title], word: session[:search_word]) %>
      </div>
      <div class="question-delete-link">
        <%= link_to "Delete", room_question_answer_path(@room, question_answer, title: session[:search_title], word: session[:search_word]), data: { turbo_method: :delete, turbo_confirm: "削除しますか？" } %>
      </div>
    </div>
  <% end %>
</div>